/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataMigrationRouteImport } from './routes/data-migration'
import { Route as CustomerAppRouteImport } from './routes/customer-app'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClientVisitsRouteImport } from './routes/client-visits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsLinksRouteImport } from './routes/tickets.links'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as PortalSlugIndexRouteImport } from './routes/portal.$slug.index'
import { Route as PortalSlugTicketsRouteImport } from './routes/portal.$slug.tickets'
import { Route as PortalSlugSolvedRouteImport } from './routes/portal.$slug.solved'
import { Route as PortalSlugProfileRouteImport } from './routes/portal.$slug.profile'
import { Route as PortalSlugDashboardRouteImport } from './routes/portal.$slug.dashboard'
import { Route as PortalSlugCreateTicketRouteImport } from './routes/portal.$slug.create-ticket'
import { Route as PortalSlugTicketsTicketIdRouteImport } from './routes/portal.$slug.tickets.$ticketId'
import { Route as CompaniesCompanyIdModulesModuleKeyRouteImport } from './routes/companies.$companyId.modules.$moduleKey'
import { Route as CompaniesCompanyIdModulesPostSalesProjectsProjectIdRouteImport } from './routes/companies.$companyId.modules.post-sales.projects.$projectId'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMigrationRoute = DataMigrationRouteImport.update({
  id: '/data-migration',
  path: '/data-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAppRoute = CustomerAppRouteImport.update({
  id: '/customer-app',
  path: '/customer-app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientVisitsRoute = ClientVisitsRouteImport.update({
  id: '/client-visits',
  path: '/client-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsLinksRoute = TicketsLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const PortalSlugIndexRoute = PortalSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugTicketsRoute = PortalSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugSolvedRoute = PortalSlugSolvedRouteImport.update({
  id: '/solved',
  path: '/solved',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugProfileRoute = PortalSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugDashboardRoute = PortalSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugCreateTicketRoute = PortalSlugCreateTicketRouteImport.update({
  id: '/create-ticket',
  path: '/create-ticket',
  getParentRoute: () => PortalSlugRoute,
} as any)
const PortalSlugTicketsTicketIdRoute =
  PortalSlugTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => PortalSlugTicketsRoute,
  } as any)
const CompaniesCompanyIdModulesModuleKeyRoute =
  CompaniesCompanyIdModulesModuleKeyRouteImport.update({
    id: '/modules/$moduleKey',
    path: '/modules/$moduleKey',
    getParentRoute: () => CompaniesCompanyIdRoute,
  } as any)
const CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute =
  CompaniesCompanyIdModulesPostSalesProjectsProjectIdRouteImport.update({
    id: '/modules/post-sales/projects/$projectId',
    path: '/modules/post-sales/projects/$projectId',
    getParentRoute: () => CompaniesCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-visits': typeof ClientVisitsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRouteWithChildren
  '/portal/$slug': typeof PortalSlugRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/links': typeof TicketsLinksRoute
  '/portal/$slug/create-ticket': typeof PortalSlugCreateTicketRoute
  '/portal/$slug/dashboard': typeof PortalSlugDashboardRoute
  '/portal/$slug/profile': typeof PortalSlugProfileRoute
  '/portal/$slug/solved': typeof PortalSlugSolvedRoute
  '/portal/$slug/tickets': typeof PortalSlugTicketsRouteWithChildren
  '/portal/$slug/': typeof PortalSlugIndexRoute
  '/companies/$companyId/modules/$moduleKey': typeof CompaniesCompanyIdModulesModuleKeyRoute
  '/portal/$slug/tickets/$ticketId': typeof PortalSlugTicketsTicketIdRoute
  '/companies/$companyId/modules/post-sales/projects/$projectId': typeof CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-visits': typeof ClientVisitsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/links': typeof TicketsLinksRoute
  '/portal/$slug/create-ticket': typeof PortalSlugCreateTicketRoute
  '/portal/$slug/dashboard': typeof PortalSlugDashboardRoute
  '/portal/$slug/profile': typeof PortalSlugProfileRoute
  '/portal/$slug/solved': typeof PortalSlugSolvedRoute
  '/portal/$slug/tickets': typeof PortalSlugTicketsRouteWithChildren
  '/portal/$slug': typeof PortalSlugIndexRoute
  '/companies/$companyId/modules/$moduleKey': typeof CompaniesCompanyIdModulesModuleKeyRoute
  '/portal/$slug/tickets/$ticketId': typeof PortalSlugTicketsTicketIdRoute
  '/companies/$companyId/modules/post-sales/projects/$projectId': typeof CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-visits': typeof ClientVisitsRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/tasks': typeof TasksRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRouteWithChildren
  '/portal/$slug': typeof PortalSlugRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/tickets/links': typeof TicketsLinksRoute
  '/portal/$slug/create-ticket': typeof PortalSlugCreateTicketRoute
  '/portal/$slug/dashboard': typeof PortalSlugDashboardRoute
  '/portal/$slug/profile': typeof PortalSlugProfileRoute
  '/portal/$slug/solved': typeof PortalSlugSolvedRoute
  '/portal/$slug/tickets': typeof PortalSlugTicketsRouteWithChildren
  '/portal/$slug/': typeof PortalSlugIndexRoute
  '/companies/$companyId/modules/$moduleKey': typeof CompaniesCompanyIdModulesModuleKeyRoute
  '/portal/$slug/tickets/$ticketId': typeof PortalSlugTicketsTicketIdRoute
  '/companies/$companyId/modules/post-sales/projects/$projectId': typeof CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-visits'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/master'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tickets'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/portal/$slug'
    | '/projects/$projectId'
    | '/support/$ticketId'
    | '/tickets/$ticketId'
    | '/tickets/links'
    | '/portal/$slug/create-ticket'
    | '/portal/$slug/dashboard'
    | '/portal/$slug/profile'
    | '/portal/$slug/solved'
    | '/portal/$slug/tickets'
    | '/portal/$slug/'
    | '/companies/$companyId/modules/$moduleKey'
    | '/portal/$slug/tickets/$ticketId'
    | '/companies/$companyId/modules/post-sales/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-visits'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/master'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tickets'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/projects/$projectId'
    | '/support/$ticketId'
    | '/tickets/$ticketId'
    | '/tickets/links'
    | '/portal/$slug/create-ticket'
    | '/portal/$slug/dashboard'
    | '/portal/$slug/profile'
    | '/portal/$slug/solved'
    | '/portal/$slug/tickets'
    | '/portal/$slug'
    | '/companies/$companyId/modules/$moduleKey'
    | '/portal/$slug/tickets/$ticketId'
    | '/companies/$companyId/modules/post-sales/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/client-visits'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/master'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tasks'
    | '/tickets'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/portal/$slug'
    | '/projects/$projectId'
    | '/support/$ticketId'
    | '/tickets/$ticketId'
    | '/tickets/links'
    | '/portal/$slug/create-ticket'
    | '/portal/$slug/dashboard'
    | '/portal/$slug/profile'
    | '/portal/$slug/solved'
    | '/portal/$slug/tickets'
    | '/portal/$slug/'
    | '/companies/$companyId/modules/$moduleKey'
    | '/portal/$slug/tickets/$ticketId'
    | '/companies/$companyId/modules/post-sales/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientVisitsRoute: typeof ClientVisitsRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CustomerAppRoute: typeof CustomerAppRoute
  DataMigrationRoute: typeof DataMigrationRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeesRoute: typeof EmployeesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LaborRoute: typeof LaborRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  ModulesRoute: typeof ModulesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RenewalsRoute: typeof RenewalsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRouteWithChildren
  TasksRoute: typeof TasksRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  TrainingRoute: typeof TrainingRoute
  VendorsRoute: typeof VendorsRoute
  PortalSlugRoute: typeof PortalSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-migration': {
      id: '/data-migration'
      path: '/data-migration'
      fullPath: '/data-migration'
      preLoaderRoute: typeof DataMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-app': {
      id: '/customer-app'
      path: '/customer-app'
      fullPath: '/customer-app'
      preLoaderRoute: typeof CustomerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-visits': {
      id: '/client-visits'
      path: '/client-visits'
      fullPath: '/client-visits'
      preLoaderRoute: typeof ClientVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/links': {
      id: '/tickets/links'
      path: '/links'
      fullPath: '/tickets/links'
      preLoaderRoute: typeof TicketsLinksRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/portal/$slug/': {
      id: '/portal/$slug/'
      path: '/'
      fullPath: '/portal/$slug/'
      preLoaderRoute: typeof PortalSlugIndexRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/tickets': {
      id: '/portal/$slug/tickets'
      path: '/tickets'
      fullPath: '/portal/$slug/tickets'
      preLoaderRoute: typeof PortalSlugTicketsRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/solved': {
      id: '/portal/$slug/solved'
      path: '/solved'
      fullPath: '/portal/$slug/solved'
      preLoaderRoute: typeof PortalSlugSolvedRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/profile': {
      id: '/portal/$slug/profile'
      path: '/profile'
      fullPath: '/portal/$slug/profile'
      preLoaderRoute: typeof PortalSlugProfileRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/dashboard': {
      id: '/portal/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/portal/$slug/dashboard'
      preLoaderRoute: typeof PortalSlugDashboardRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/create-ticket': {
      id: '/portal/$slug/create-ticket'
      path: '/create-ticket'
      fullPath: '/portal/$slug/create-ticket'
      preLoaderRoute: typeof PortalSlugCreateTicketRouteImport
      parentRoute: typeof PortalSlugRoute
    }
    '/portal/$slug/tickets/$ticketId': {
      id: '/portal/$slug/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/portal/$slug/tickets/$ticketId'
      preLoaderRoute: typeof PortalSlugTicketsTicketIdRouteImport
      parentRoute: typeof PortalSlugTicketsRoute
    }
    '/companies/$companyId/modules/$moduleKey': {
      id: '/companies/$companyId/modules/$moduleKey'
      path: '/modules/$moduleKey'
      fullPath: '/companies/$companyId/modules/$moduleKey'
      preLoaderRoute: typeof CompaniesCompanyIdModulesModuleKeyRouteImport
      parentRoute: typeof CompaniesCompanyIdRoute
    }
    '/companies/$companyId/modules/post-sales/projects/$projectId': {
      id: '/companies/$companyId/modules/post-sales/projects/$projectId'
      path: '/modules/post-sales/projects/$projectId'
      fullPath: '/companies/$companyId/modules/post-sales/projects/$projectId'
      preLoaderRoute: typeof CompaniesCompanyIdModulesPostSalesProjectsProjectIdRouteImport
      parentRoute: typeof CompaniesCompanyIdRoute
    }
  }
}

interface CompaniesCompanyIdRouteChildren {
  CompaniesCompanyIdModulesModuleKeyRoute: typeof CompaniesCompanyIdModulesModuleKeyRoute
  CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute: typeof CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute
}

const CompaniesCompanyIdRouteChildren: CompaniesCompanyIdRouteChildren = {
  CompaniesCompanyIdModulesModuleKeyRoute:
    CompaniesCompanyIdModulesModuleKeyRoute,
  CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute:
    CompaniesCompanyIdModulesPostSalesProjectsProjectIdRoute,
}

const CompaniesCompanyIdRouteWithChildren =
  CompaniesCompanyIdRoute._addFileChildren(CompaniesCompanyIdRouteChildren)

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRouteWithChildren
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRouteWithChildren,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SupportRouteChildren {
  SupportTicketIdRoute: typeof SupportTicketIdRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketIdRoute: SupportTicketIdRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TicketsLinksRoute: typeof TicketsLinksRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TicketsLinksRoute: TicketsLinksRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface PortalSlugTicketsRouteChildren {
  PortalSlugTicketsTicketIdRoute: typeof PortalSlugTicketsTicketIdRoute
}

const PortalSlugTicketsRouteChildren: PortalSlugTicketsRouteChildren = {
  PortalSlugTicketsTicketIdRoute: PortalSlugTicketsTicketIdRoute,
}

const PortalSlugTicketsRouteWithChildren =
  PortalSlugTicketsRoute._addFileChildren(PortalSlugTicketsRouteChildren)

interface PortalSlugRouteChildren {
  PortalSlugCreateTicketRoute: typeof PortalSlugCreateTicketRoute
  PortalSlugDashboardRoute: typeof PortalSlugDashboardRoute
  PortalSlugProfileRoute: typeof PortalSlugProfileRoute
  PortalSlugSolvedRoute: typeof PortalSlugSolvedRoute
  PortalSlugTicketsRoute: typeof PortalSlugTicketsRouteWithChildren
  PortalSlugIndexRoute: typeof PortalSlugIndexRoute
}

const PortalSlugRouteChildren: PortalSlugRouteChildren = {
  PortalSlugCreateTicketRoute: PortalSlugCreateTicketRoute,
  PortalSlugDashboardRoute: PortalSlugDashboardRoute,
  PortalSlugProfileRoute: PortalSlugProfileRoute,
  PortalSlugSolvedRoute: PortalSlugSolvedRoute,
  PortalSlugTicketsRoute: PortalSlugTicketsRouteWithChildren,
  PortalSlugIndexRoute: PortalSlugIndexRoute,
}

const PortalSlugRouteWithChildren = PortalSlugRoute._addFileChildren(
  PortalSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientVisitsRoute: ClientVisitsRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CustomerAppRoute: CustomerAppRoute,
  DataMigrationRoute: DataMigrationRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeesRoute: EmployeesRoute,
  IntegrationsRoute: IntegrationsRoute,
  LaborRoute: LaborRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  ModulesRoute: ModulesRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RenewalsRoute: RenewalsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRouteWithChildren,
  TasksRoute: TasksRoute,
  TicketsRoute: TicketsRouteWithChildren,
  TrainingRoute: TrainingRoute,
  VendorsRoute: VendorsRoute,
  PortalSlugRoute: PortalSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
