/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataMigrationRouteImport } from './routes/data-migration'
import { Route as CustomerAppRouteImport } from './routes/customer-app'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMigrationRoute = DataMigrationRouteImport.update({
  id: '/data-migration',
  path: '/data-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAppRoute = CustomerAppRouteImport.update({
  id: '/customer-app',
  path: '/customer-app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customer-app': typeof CustomerAppRoute
  '/data-migration': typeof DataMigrationRoute
  '/documents': typeof DocumentsRoute
  '/employees': typeof EmployeesRoute
  '/integrations': typeof IntegrationsRoute
  '/labor': typeof LaborRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRouteWithChildren
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/projects/$projectId'
    | '/support/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/projects/$projectId'
    | '/support/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/customer-app'
    | '/data-migration'
    | '/documents'
    | '/employees'
    | '/integrations'
    | '/labor'
    | '/login'
    | '/modules'
    | '/onboarding'
    | '/projects'
    | '/renewals'
    | '/reports'
    | '/settings'
    | '/support'
    | '/training'
    | '/vendors'
    | '/companies/$companyId'
    | '/projects/$projectId'
    | '/support/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CustomerAppRoute: typeof CustomerAppRoute
  DataMigrationRoute: typeof DataMigrationRoute
  DocumentsRoute: typeof DocumentsRoute
  EmployeesRoute: typeof EmployeesRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LaborRoute: typeof LaborRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RenewalsRoute: typeof RenewalsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRouteWithChildren
  TrainingRoute: typeof TrainingRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-migration': {
      id: '/data-migration'
      path: '/data-migration'
      fullPath: '/data-migration'
      preLoaderRoute: typeof DataMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-app': {
      id: '/customer-app'
      path: '/customer-app'
      fullPath: '/customer-app'
      preLoaderRoute: typeof CustomerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SupportRouteChildren {
  SupportTicketIdRoute: typeof SupportTicketIdRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketIdRoute: SupportTicketIdRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CustomerAppRoute: CustomerAppRoute,
  DataMigrationRoute: DataMigrationRoute,
  DocumentsRoute: DocumentsRoute,
  EmployeesRoute: EmployeesRoute,
  IntegrationsRoute: IntegrationsRoute,
  LaborRoute: LaborRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RenewalsRoute: RenewalsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRouteWithChildren,
  TrainingRoute: TrainingRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
