/**
 * Buildesk client-portal chatbot knowledge base.
 * Used by the portal live-chat widget (Buildesk Assistant).
 */

export type ChatbotCategory =
  | "portal"
  | "tickets"
  | "product"
  | "billing"
  | "onboarding"
  | "support";

export type ChatbotArticle = {
  id: string;
  category: ChatbotCategory;
  /** Shown on quick-reply chips in the chat widget */
  quickReplyLabel?: string;
  keywords: string[];
  /** Tie-breaker when multiple articles match (higher wins) */
  priority: number;
  response: string;
  /** Routes to a live agent instead of showing response text */
  escalate?: boolean;
};

export const CHATBOT_GREETING =
  "Hi! I'm the Buildesk Assistant. I can help with tickets, onboarding questions, billing, and more. Pick a topic below or type your question.";

export const CHATBOT_FALLBACK =
  "I'm not sure I understood that. Try asking about your tickets, how to create a request, or billing. You can also tap **Talk to a person** to reach our team.";

export const CHATBOT_ESCALATING =
  "Connecting you to a support executive… Someone from our team will join this chat shortly.";

export const CHATBOT_KNOWLEDGE: ChatbotArticle[] = [
  // ── Portal navigation ──────────────────────────────────────────────
  {
    id: "portal-dashboard",
    category: "portal",
    quickReplyLabel: "Portal help",
    keywords: [
      "portal",
      "dashboard",
      "home page",
      "where do i go",
      "navigation",
      "menu",
      "how to use portal",
    ],
    priority: 5,
    response:
      "Your client portal has five main areas:\n\n• **Dashboard** — summary of your open tickets\n• **Create New Ticket** — submit a design or support request\n• **My Tickets** — active tickets you're working on with our team\n• **Solved Tickets** — resolved and closed requests\n• **Profile** — your contact details\n\nUse the menu on the left (or bottom bar on mobile) to switch between them.",
  },
  {
    id: "portal-create-ticket",
    category: "portal",
    quickReplyLabel: "Create a ticket",
    keywords: [
      "create ticket",
      "new ticket",
      "raise ticket",
      "submit request",
      "open request",
      "how to create",
      "file a ticket",
      "report issue",
      "log issue",
    ],
    priority: 8,
    response:
      "To create a ticket:\n\n1. Open **Create New Ticket** from the portal menu\n2. Enter a clear **subject** and detailed **description**\n3. Choose a **category** (e.g. Design, Bug, Feature Request)\n4. Set **priority** (Low / Medium / High)\n5. Submit — you'll get a ticket number like **DT-001**\n\nOur team is notified immediately and will reply in the ticket thread. You can track progress under **My Tickets**.",
  },
  {
    id: "portal-profile",
    category: "portal",
    keywords: ["profile", "my details", "contact name", "email", "update profile", "my account"],
    priority: 4,
    response:
      "Your **Profile** page shows the contact name and email linked to this portal. If any details need updating, mention it here and we can connect you with your account manager.",
  },
  {
    id: "portal-link-inactive",
    category: "portal",
    keywords: [
      "link not working",
      "portal inactive",
      "link expired",
      "cannot access",
      "access denied",
      "invalid link",
    ],
    priority: 6,
    response:
      "If your portal link shows as inactive or invalid, it may have been regenerated by your account manager. Please ask your Buildesk contact for an updated link — old links stop working after regeneration.",
  },

  // ── Tickets ────────────────────────────────────────────────────────
  {
    id: "ticket-status",
    category: "tickets",
    quickReplyLabel: "Ticket status",
    keywords: [
      "ticket status",
      "track ticket",
      "ticket update",
      "progress on ticket",
      "where is my ticket",
      "check status",
      "ticket number",
    ],
    priority: 9,
    response:
      "You can track tickets under **My Tickets** in the portal. Each ticket shows its status:\n\n• **Open** — received, awaiting triage\n• **In Progress** — our team is working on it\n• **Resolved** — fix delivered, pending your confirmation\n• **Closed** — completed\n\nShare your ticket number (e.g. **DT-003**) here and I can look it up for you.",
  },
  {
    id: "ticket-open-list",
    category: "tickets",
    quickReplyLabel: "My open tickets",
    keywords: [
      "my tickets",
      "open tickets",
      "active tickets",
      "pending tickets",
      "how many tickets",
      "list tickets",
    ],
    priority: 7,
    response:
      "Open **My Tickets** in the portal to see everything still in progress (Open or In Progress). Resolved and closed items move to **Solved Tickets**.",
  },
  {
    id: "ticket-reply",
    category: "tickets",
    keywords: [
      "reply",
      "respond",
      "add message",
      "comment on ticket",
      "attach file",
      "attachment",
      "upload screenshot",
    ],
    priority: 6,
    response:
      "Open the ticket from **My Tickets**, scroll to the conversation thread, type your message, and send. You can add context or screenshots anytime — our team sees updates in real time.",
  },
  {
    id: "ticket-categories",
    category: "tickets",
    keywords: [
      "category",
      "banner design",
      "dashboard issue",
      "design request",
      "development",
      "bug report",
      "feature request",
      "what category",
    ],
    priority: 5,
    response:
      "When creating a ticket, pick the category that best fits:\n\n• **Banner Design** — marketing creatives, banners\n• **Dashboard Issue** — CRM/ERP dashboard problems\n• **Design** — UI/UX or visual changes\n• **Development** — custom build work\n• **Bug** — something broken or incorrect\n• **Feature Request** — new capability you'd like\n• **Other** — anything else\n\nChoosing the right category helps us route your request faster.",
  },
  {
    id: "ticket-priority",
    category: "tickets",
    keywords: ["priority", "urgent", "critical", "high priority", "how fast", "response time", "sla"],
    priority: 6,
    response:
      "Set ticket priority when submitting:\n\n• **High** — blocking your work or production issue\n• **Medium** — important but not blocking (default)\n• **Low** — minor enhancement or cosmetic change\n\nFor urgent production outages, create a High-priority ticket **and** tap **Talk to a person** so we can escalate immediately.",
  },
  {
    id: "ticket-resolved-vs-closed",
    category: "tickets",
    keywords: ["resolved", "closed", "solved", "completed", "done", "reopen"],
    priority: 4,
    response:
      "**Resolved** means our team has delivered a fix — please verify and reply if anything is still outstanding. **Closed** means the request is fully complete. Resolved tickets appear under **Solved Tickets**. Need to reopen? Reply on the ticket or create a follow-up request.",
  },
  {
    id: "ticket-vs-support-desk",
    category: "tickets",
    keywords: ["support desk", "tkt", "engineering ticket", "internal ticket", "difference"],
    priority: 3,
    response:
      "Requests you raise through this **client portal** are tracked as client tickets (numbers like **DT-001**). Our internal engineering team may also track related technical work separately — you don't need to worry about that. Always use this portal or live chat for anything you need from us.",
  },

  // ── Live chat ──────────────────────────────────────────────────────
  {
    id: "live-chat",
    category: "support",
    keywords: [
      "live chat",
      "chat widget",
      "this chat",
      "chat history",
      "convert to ticket",
    ],
    priority: 5,
    response:
      "You're in **live chat** with the Buildesk Assistant. I can answer common questions instantly. For complex issues, tap **Talk to a person** and a team member will join.\n\nYou can also use **Convert to ticket** at the bottom of the chat to save this conversation as a formal request.",
  },
  {
    id: "talk-to-person",
    category: "support",
    quickReplyLabel: "Talk to a person",
    keywords: [
      "talk to person",
      "talk to human",
      "speak to agent",
      "speak to someone",
      "real person",
      "support executive",
      "connect me",
      "agent",
      "representative",
      "call me",
    ],
    priority: 10,
    response: "__ESCALATE__",
    escalate: true,
  },

  // ── Billing ──────────────────────────────────────────────────────────
  {
    id: "billing",
    category: "billing",
    quickReplyLabel: "Billing question",
    keywords: [
      "billing",
      "invoice",
      "payment",
      "pay",
      "renewal",
      "amc",
      "annual maintenance",
      "subscription",
      "plan",
      "pricing",
      "outstanding",
      "dues",
    ],
    priority: 8,
    response:
      "For billing, invoices, renewals, or AMC questions, our accounts team is best placed to help. Share your company name and invoice reference if you have one.\n\nWould you like me to connect you with a support executive?",
  },
  {
    id: "renewal",
    category: "billing",
    keywords: ["renew", "renewal date", "contract expiry", "license expiry", "extend plan"],
    priority: 7,
    response:
      "Plan renewals are handled by your account manager. They'll reach out before your renewal date with terms and payment details. For renewal status or to request an early renewal quote, tap **Talk to a person** or create a ticket under category **Other**.",
  },

  // ── Product & onboarding ─────────────────────────────────────────────
  {
    id: "what-is-buildesk",
    category: "product",
    keywords: [
      "what is buildesk",
      "about buildesk",
      "your product",
      "crm",
      "erp",
      "real estate software",
      "what do you do",
    ],
    priority: 6,
    response:
      "Buildesk provides **real-estate CRM and ERP software** for developers and brokers — sales, inventory, bookings, payments, customer app, vendor management, and more. Your team is onboarding onto the platform; this portal is where you raise design, support, and customization requests during and after go-live.",
  },
  {
    id: "onboarding-help",
    category: "onboarding",
    quickReplyLabel: "Onboarding help",
    keywords: [
      "onboarding",
      "go live",
      "go-live",
      "implementation",
      "setup",
      "getting started",
      "training",
      "checklist",
      "migration",
      "data upload",
      "when will we go live",
    ],
    priority: 7,
    response:
      "Onboarding typically covers:\n\n1. **Project setup** and module configuration\n2. **Data migration** (units, customers, bookings)\n3. **Document collection** and checklist completion\n4. **Training** for your team\n5. **Go-live** once everything is verified\n\nYour Buildesk onboarding manager coordinates each step. For status on your specific project, create a ticket or speak with our team.",
  },
  {
    id: "data-migration",
    category: "onboarding",
    keywords: [
      "data migration",
      "excel upload",
      "import data",
      "upload sheet",
      "customer data",
      "unit data",
      "booking data",
    ],
    priority: 5,
    response:
      "Data migration is done using structured Excel templates for units, customers, bookings, and payments. Your onboarding manager will share the correct templates and validate uploads. If you're stuck on a specific sheet or seeing errors, create a ticket with category **Development** and attach a screenshot of the issue.",
  },
  {
    id: "customer-app",
    category: "product",
    keywords: [
      "customer app",
      "mobile app",
      "buyer app",
      "white label",
      "branding",
      "app publish",
    ],
    priority: 5,
    response:
      "The **Customer App** lets your buyers track bookings and payments. It can run as Buildesk-branded or white-label with your logo and colours. Branding and publish settings are configured during onboarding. For app issues after go-live, create a ticket under **Dashboard Issue** or **Bug**.",
  },
  {
    id: "training",
    category: "onboarding",
    keywords: ["training", "session", "demo", "walkthrough", "learn", "how to use"],
    priority: 5,
    response:
      "We run training sessions for your team during onboarding — covering CRM workflows, inventory, bookings, and reports. Session recordings are shared when available. To schedule additional training, create a ticket or ask to speak with your account manager.",
  },

  // ── General support ──────────────────────────────────────────────────
  {
    id: "business-hours",
    category: "support",
    keywords: ["hours", "working hours", "business hours", "when are you open", "availability"],
    priority: 4,
    response:
      "Our support team is available on business days (Mon–Sat). Messages sent outside hours are picked up on the next working day. For urgent production issues, create a **High** priority ticket and use **Talk to a person**.",
  },
  {
    id: "thank-you",
    category: "support",
    keywords: ["thank you", "thanks", "thankyou", "appreciate", "great help"],
    priority: 2,
    response:
      "You're welcome! If you need anything else, I'm here. You can also browse **My Tickets** anytime or reach our team via live chat.",
  },
  {
    id: "goodbye",
    category: "support",
    keywords: ["bye", "goodbye", "see you", "that's all", "nothing else"],
    priority: 2,
    response: "Goodbye! Feel free to open the chat again whenever you need help. Have a great day!",
  },
];

/** Quick-reply chips shown in the portal chat widget */
export const CHATBOT_QUICK_REPLY_LABELS = CHATBOT_KNOWLEDGE.filter(
  (a) => a.quickReplyLabel,
).map((a) => a.quickReplyLabel!);
